---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.yml"
- name: Setup RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_facts.os_family == 'RedHat'
- name: Setup Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_facts.os_family == 'Debian'
- name: Ensure dependencies are installed.
  ansible.builtin.package:
    name: curl
    state: present
- name: Install Kubernetes packages.
  ansible.builtin.package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  notify: restart kubelet
  with_items: "{{ kubernetes_packages }}"
- name: Setup Sysctl
  ansible.builtin.include_tasks: sysctl-setup.yml
- name: Setup Kubelet
  ansible.builtin.include_tasks: kubelet-setup.yml
  when: kubernetes_kubelet_extra_args|length > 0
- name: Ensure kubelet is started and enabled at boot.
  ansible.builtin.service:
    enabled: true
    name: kubelet
    state: started
- name: Check if Kubernetes has already been initialized.
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat
- name: Setup Master
  ansible.builtin.include_tasks: master-setup.yml
  when: kubernetes_role == 'master'
- name: Get the kubeadm join command from the Kubernetes master.
  ansible.builtin.command: kubeadm token create --print-join-command
  changed_when: false
  register: kubernetes_join_command_result
  when: kubernetes_role == 'master'
- name: Set the kubeadm join command globally.
  ansible.builtin.set_fact:
    kubernetes_join_command: "{{ kubernetes_join_command_result.stdout }} {{ kubernetes_join_command_extra_opts }}\n"
  delegate_facts: true
  delegate_to: "{{ item }}"
  when: kubernetes_join_command_result.stdout is defined
  with_items: "{{ groups['all'] }}"
- name: Setup Node
  ansible.builtin.include_tasks: node-setup.yml
  when: kubernetes_role == 'node'
