---
- name: sysctl-setup | Ensure procps is installed.
  ansible.builtin.package:
    name: "{{ procps_package }}"
    state: present
  when: "ansible_facts.distribution != 'Debian' or ansible_facts.distribution_major_version | int < 10\n"
- name: sysctl-setup | Let iptables see bridged traffic.
  ansible.posix.sysctl:
    name: "{{ item }}"
    state: present
    value: "1"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: "ansible_facts.distribution != 'Debian' or ansible_facts.distribution_major_version | int < 10\n"
