---
- name: Restart kubelet
  ansible.builtin.systemd:
    daemon_reload: true
    name: kubelet
    state: restarted
- name: Refresh Kubernetes dnf cache
  ansible.builtin.dnf:
    disablerepo: "*"
    enablerepo: kubernetes
    state: present
